### ISSUE TITLE
One integration for every county needed?

### ISSUE THREAD

**Issue by waldmeisterx** [foosel/homeassistant-coronavirus-hessen#1]
Hi foosel,
nice work, now I keep updated für Kreis Bergstraße in HA. :-)
I integrated in HA via HACS. 
At the moment I have to do an integration for each county to get more than one sensor?
Do I have to do special configuration to get the "stacked" view like in your new screenshot?
![image](https://user-images.githubusercontent.com/2168391/76702267-cc948800-66c8-11ea-8a8b-738cc44e2969.png)

I even do not get the last update time. Am I missing something?
And I can't change the display names, because the entities are readonly.
![image](https://user-images.githubusercontent.com/2168391/76702299-06fe2500-66c9-11ea-85a1-401ee75dfdfe.png)

Regards

**Comment by foosel** [comment]
> At the moment I have to do an integration for each county to get more than one sensor?

Sadly yes. I'm still learning how all this stuff works in HA and this is one of the things I'm hoping to figure out soon 😅



> Do I have to do special configuration to get the "stacked" view like in your new screenshot?

Yeah... I use the `fold-entity-row` custom card for that:

``` yaml
              - type: custom:fold-entity-row
                head: 
                  entity: sensor.coronavirus_hessen
                  secondary_info: last-changed
                entities:
                  - sensor.coronavirus_hessen_offenbach_landkreis
                  - sensor.coronavirus_hessen_main_kinzig_kreis
                  - sensor.coronavirus_hessen_wetteraukreis
                  - sensor.coronavirus_hessen_frankfurt
```

The `secondary_info: last-changed` bit is also what you are looking for with regards to your last update date & time.

> And I can't change the display names, because the entities are readonly.

Another thing I have no idea at the moment how to fix - I simply changed the name via a customization.

Sorry - total noob 😅
